version: '3'

services:
  doctissimo-api-nginx:
    container_name: doctissimo-api-nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './:/var/www/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8081:80
    depends_on:
      - doctissimo-api-php

  doctissimo-api-php:
    container_name: doctissimo-api-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    volumes:
      - ./:/var/www/app

  doctissimo-api-mysql:
    container_name: doctissimo-api-mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctissimo